### ISSUE TITLE
[PE-D][Tester A] Help command

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14b-1/tp#190]
**Description**
Although the current `help `command does list all its available commands and does provide a link to the user guide, I do not believe it is sufficient to familiarise the new users with the commands (as stated in the user stories)

![image.png](https://raw.githubusercontent.com/OttoTan/ped/main/files/0bbae1c5-3107-4f84-bfec-093f0b275be1.png)

**Suggestion**
Perhaps you could improve the UI by providing the parameters needed and examples in a table form

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: OttoTan/ped#3

**Comment by Gra7ityIC3** [comment]
> Perhaps you could improve the UI by providing the parameters needed and examples in a table form

We're not allowed to make any UI enhancements in v1.6.
