### ISSUE TITLE
[PE-D][Tester E] App does not support "S/O" in names

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14b-1/tp#206]
![image.png](https://raw.githubusercontent.com/seanlim/ped/main/files/0080eb5d-4184-4273-bed5-757c168e6e24.png)

**Steps to reproduce:** 
1. Add a user with the name "John Doe S/O John Deez"

It might affect users who want to add contact with "s/o" in their legal name

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: seanlim/ped#4

**Comment by Gra7ityIC3** [comment]
We should include this constraint in the user guide, specifying that users should use `son of` instead of `s/o`.
