### ISSUE TITLE
[PE-D][Tester B] Wrong error message for very large family size

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14b-1/tp#207]
Expected: The error message displayed should indicate the limit to which the app can take the family size input
Actual: The error message is `Family size should be a positive integer` when the input family size is indeed a positive integer
Steps to reproduce:
1. Input command: `add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 dob/1999-03-09 famsize/300000000000000000000000000000000000000000000000000000000 income/1000`
2. Error message displayed is `Family size should be a positive integer`

![image.png](https://raw.githubusercontent.com/Virusrwj223/ped/main/files/a4bc28c9-4129-4819-ad67-16a6296e59d1.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Virusrwj223/ped#5

**Comment by LeongWZ** [comment]
Perhaps the message could be changed to `Family size should be a positive integer not exceeding 2^31 - 1`

**Comment by Gra7ityIC3** [comment]
This is an [extreme user behavior](https://nus-cs2103-ay2425s1.github.io/website/admin/tp-pe.html#functionality-bugs-2:~:text=Problems%20caused%20by%20extreme%20user%20behaviors%3A) that happens only when the input entered is larger than the maximum value of an integer.

We could have made the error message more specific as mentioned by @LeongWZ, but that isn't allowed in v1.6.
