### ISSUE TITLE
[PE-D][Tester B] Name of person with long name truncated

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14b-1/tp#213]
Expected: Long names should be fully viewed in the UI for person list
Actual: Long names are truncated and ends of with '...'
Steps to reproduce:
1. Input command `add n/John Doe aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 dob/1999-03-09 famsize/3 income/1000`
2. Name has been truncated and not clearly screen even with person list UI component maximised

![image.png](https://raw.githubusercontent.com/Virusrwj223/ped/main/files/7224fd32-5c61-4b13-979e-147b053af32b.png)

Tip from tester:
Consider placing a character limit in the input and justify the rationale in the UG.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Virusrwj223/ped#8

**Comment by Gra7ityIC3** [comment]
> Consider placing a character limit in the input and justify the rationale in the UG.

See Q8 of the feature freeze FAQs:

![image](https://github.com/user-attachments/assets/d1057b8d-2eef-45c3-a9ea-5b7b4d678707)

You should be able to view the name using `find` and `get`. E.g., `find n/aaaaa` and `get name`.
