### ISSUE TITLE
[PE-D][Tester A] Sort Command (Parameters shown)

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14b-1/tp#217]
**Description**
Although the parameters provided are listed in the command summary, it is not listed in the feature list, as shown below

![image.png](https://raw.githubusercontent.com/OttoTan/ped/main/files/e6e795a8-241f-4af9-9ed9-370a00f21de2.png)

**Suggestions**
This may lead to the users being confused about what parameters are available for use, especially if they have not seen the command summary which is at the bottom of the guide. 

Perhaps you can also list out the parameters available at the beginning

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: OttoTan/ped#12

**Comment by arjun2598** [comment]
The parameters were listed directly below the line in the screenshot but the suggestion is valid and would help make the parameters more directly apparent. Hence, the format will be changed to include the available parameters directly.
