### ISSUE TITLE
[PE-D][Tester E] App does not save data on force quit

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14b-1/tp#221]
Reporting this because I noticed that yall save data on `cmd+Q`, so yall might want to cover force quits and crashes also!

**Steps to produce:**
1. Delete any existing data files
2. launch the app (the app should start with sample data)
3. force quit the app with task manager
4. the app doesn't save `data`

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: seanlim/ped#9

**Comment by Gra7ityIC3** [comment]
Similar to https://github.com/AY2425S1-CS2103T-F14b-1/tp/issues/225#issuecomment-2466640163.
