### ISSUE TITLE
[PE-D][Tester B] The DG contains a feature that is already implemented

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14b-1/tp#233]
Expected: The Undo feature should not be a proposed feature as it is implemented
Actual: The Undo feature is labelled a proposed feature

![image.png](https://raw.githubusercontent.com/Virusrwj223/ped/main/files/4e9d90aa-b559-4352-a8a2-91ee001eb157.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Virusrwj223/ped#15

**Comment by Gra7ityIC3** [comment]
Duplicate of #189.
