### ISSUE TITLE
Deleting duplicate indexes fails silently

### ISSUE THREAD

**Issue by Gra7ityIC3** [AY2425S1-CS2103T-F14b-1/tp#96]
If the user enters the same index multiple times when deleting, e.g., `delete 6, 6, 6`, the person at index 6 is deleted but no error message is shown on the UI when the application tries to delete the same index again. Moreover, the deletion doesn't persist since it requires all deletions to be successful.

**Comment by nws321** [comment]
Thanks for the catch, I have fixed it to disregard duplicated valid indexes such that it will still delete the unique index values in my PR.
